/**
 * Ferret Server API
 * API of Ferret Server
 *
 * OpenAPI spec version: 1.0.0-rc.2
 * Contact: mont.ferret@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The properties that are shared amongst all versions of the Data model.
 */
export interface DataCommon {
    jobId: string;
    scriptId: string;
    scriptRev: string;
    value: any;
}
