/**
 * Ferret Server API
 * API of Ferret Server
 *
 * OpenAPI spec version: 0.1
 * Contact: ziflex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The properties that are allowed when creating or updating a Execution.
 */
export interface ExecutionInput {
    scriptID: string;
    params?: { [key: string]: any; };
}
