/**
 * Ferret Server API
 * API of Ferret Server
 *
 * OpenAPI spec version: 1.0.0-rc.2
 * Contact: mont.ferret@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutionCause } from './executionCause';
import { ExecutionStatus } from './executionStatus';

/**
 * The properties that are shared amongst all versions of the Execution model.
 */
export interface ExecutionCommon {
    jobId: string;
    scriptId: string;
    scriptRev: string;
    status: ExecutionStatus;
    cause: ExecutionCause;
}
