/**
 * Ferret Server API
 * API of Ferret Server
 *
 * OpenAPI spec version: 1.0.0-rc.2
 * Contact: mont.ferret@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScriptExecution } from './scriptExecution';
import { ScriptPersistence } from './scriptPersistence';

/**
 * The properties that are shared amongst all versions of the Script model.
 */
export interface ScriptCommon {
    name: string;
    description?: string;
    execution: ScriptExecution;
    persistence: ScriptPersistence;
}
