/**
 * Ferret Server API
 * API of Ferret Server
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * Contact: mont.ferret@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Entity } from './entity';
import { ScriptCommon } from './scriptCommon';
import { ScriptExecution } from './scriptExecution';
import { ScriptPersistence } from './scriptPersistence';

export interface ScriptEntity {
    id: string;
    rev: string;
    createdAt: string;
    updatedAt?: string;
    name: string;
    description?: string;
    execution: ScriptExecution;
    persistence: ScriptPersistence;
}
